import { Router } from 'express';
import * as c from '../controllers/orderController.js';
import { authenticate } from '../middleware/auth.js';
import { uploadReturnEvidence, withMulterErrors } from '../middleware/upload.js';
const r = Router();
r.use(authenticate);
r.post('/place',        c.placeOrder);
r.get('/list',          c.listOrders);
r.put('/cancel',        c.cancelOrder);
r.put('/return',        withMulterErrors(uploadReturnEvidence), c.returnOrder);
r.get('/track/:orderId', c.trackOrder);
r.get('/:orderId',      c.getOrder);
r.put('/:orderId/status', c.updateOrderStatus);
export default r;